version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: ./src
    volumes:
      - ./src:/app

    environment:
      APP_ENVIRONMENT: local
      DB_HOST: new_table
      DB_USER: dbuser
      DB_PASS: root12345
      DB_NAME: dbtest

    command: bash -c "./docker-entrypoint.sh"

  db:
    image: mysql:5.6
    restart: always
    ports:
      - 6306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbtest
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: root12345
