version: 1
formatters:
  simple:
    format: '[%(levelname)s] %(message)s'
    # format: '[%(asctime)s] %(levelname)s: %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'
    # format: '[%(asctime)s] (%(name)s) %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]


